List<Map<String, dynamic>> projectList = [
  {
    "projectName": "Hotaya",
    "jobTitle": "Flutter Developer",
    "companyName": "Digital Orbis Creators LLP",
    "url": "https://www.digitalorbiscreators.org/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/f6UEnbepFbRR3Jc0YO9eRLU7clq7pjxVO-ZIy9kgJE7ob7stzQb43rOXFkKNJk-v50tz=w240-h480-rw",
    "appUrl": "https://play.google.com/store/apps/details?id=com.app.hotaya",
  },
  {
    "projectName": "Partzbazaar",
    "jobTitle": "Flutter Developer",
    "companyName": "Digital Orbis Creators LLP",
    "url": "https://www.digitalorbiscreators.org/",
    "description": "",
    "imageURL": "",
    "appUrl": "",
  },
  {
    "projectName": "Metaconsult",
    "jobTitle": "Flutter Developer",
    "companyName": "Digital Orbis Creators LLP",
    "url": "https://www.digitalorbiscreators.org/",
    "description": "",
    "imageURL":
        "https://www.metaconsult.in/wp-content/uploads/2022/07/Logo.png.jpg.png",
    "appUrl": "https://metaconsultapp.com/",
  },
  {
    "projectName": "MBIO TECH",
    "jobTitle": "Flutter Developer",
    "companyName": "Digital Orbis Creators LLP",
    "url": "https://www.digitalorbiscreators.org/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/K1asj7SRNF9CdMRFn0G5T38o-ayQ6TTci3xNUMoIzArIxm7lzFTDS4cOqG7iss-WycM=w240-h480-rw",
    "appUrl": "https://play.google.com/store/apps/details?id=com.app.mbio",
  },
  {
    "projectName": "Just Touch",
    "jobTitle": "Flutter Developer",
    "companyName": "Digital Orbis Creators LLP",
    "url": "https://www.digitalorbiscreators.org/",
    "description": "",
    "imageURL": "",
    "appUrl": "",
  },
  {
    "projectName": "Guidely",
    "jobTitle": "Flutter Developer",
    "companyName": "IGuider Learning Pvt Ltd(Guidely)",
    "url": "https://guidely.in/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/e6A3f28baYLyUy8Xm-_oVHyt0s5BWORsHrvqar47LcDpvT5wxckW2tjMD2ExzK-tfw=w240-h480-rw",
    "appUrl":
        "https://play.google.com/store/apps/details?id=apps.ibpsguide.com",
  },
  {
    "projectName": "Crack With Jack",
    "jobTitle": "Flutter Developer",
    "companyName": "IGuider Learning Pvt Ltd(Guidely)",
    "url": "https://guidely.in/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/7XXYdBMzWBY6JmPLGJR_7-sJuU7FB_JIByeDUAyhYn0RhFd6YQTj7vHL8roK_CrV9wU=w240-h480-rw",
    "appUrl":
        "https://play.google.com/store/apps/details?id=crackwithjack.ibpsguide.com",
  },
  {
    "projectName": "Competitive Exams Library",
    "jobTitle": "Flutter Developer",
    "companyName": "IGuider Learning Pvt Ltd(Guidely)",
    "url": "https://guidely.in/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/7ZUunNATjP3pvO6UJbUxYIGBCatUBaFJCWiu2usVt2mRprpOP9ecKi7NM1IuOX6FbsU=w240-h480-rw",
    "appUrl":
        "https://play.google.com/store/apps/details?id=app.competitiveexamslibrary.com",
  },
  {
    "projectName": "Online study Point",
    "jobTitle": "Flutter Developer",
    "companyName": "IGuider Learning Pvt Ltd(Guidely)",
    "url": "https://guidely.in/",
    "description": "",
    "imageURL": "",
    "appUrl":
        "https://play.google.com/store/apps/details?id=com.in.onlinestudypoint",
  },
  {
    "projectName": "SSC Maker",
    "jobTitle": "Flutter Developer",
    "companyName": "IGuider Learning Pvt Ltd(Guidely)",
    "url": "https://guidely.in/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/kQb1NNG6vmZ2_cjFlN-z4wJWxpcx6_yXFCcP0ivTl8pwIgeJNMj_yX9iosiAZbYbe16H=w240-h480-rw",
    "appUrl": "https://play.google.com/store/apps/details?id=com.sscmaker.ssc",
  },
  {
    "projectName": "Studyniti",
    "jobTitle": "Flutter Developer",
    "companyName": "IGuider Learning Pvt Ltd(Guidely)",
    "url": "https://guidely.in/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/en0Lj0mFmi_fRHeEXNv7IoNjtSngYZHN-7WMYJ_1E6y-irSgqRsnt3n07J-6XcHImzA=w240-h480-rw",
    "appUrl":
        "https://play.google.com/store/apps/details?id=apps.studyniti.com",
  },
  {
    "projectName": "Bankerspoint",
    "jobTitle": "Flutter Developer",
    "companyName": "IGuider Learning Pvt Ltd(Guidely)",
    "url": "https://guidely.in/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/9OwYFAQVI8SVOe5QZHRmcSgTbUQAe94-Q4aFZL6o9ZcnkW8-M0ILNEYw5MHR9kQUBEE=w240-h480-rw",
    "appUrl":
        "https://play.google.com/store/apps/details?id=com.bankerspoint.app",
  },
  {
    "projectName": "Exam Pundit",
    "jobTitle": "Flutter Developer",
    "companyName": "IGuider Learning Pvt Ltd(Guidely)",
    "url": "https://guidely.in/",
    "description": "",
    "imageURL": "",
    "appUrl": "",
  },
  {
    "projectName": "Successkey98",
    "jobTitle": "Flutter Developer",
    "companyName": "IGuider Learning Pvt Ltd(Guidely)",
    "url": "https://guidely.in/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/1CInWP6fIcluZzLKz8jP4h4rMPulbYlmeVAxMMpSgIgYg_bLc9ZyKTHcGtLV9b3ypIzS=w240-h480-rw",
    "appUrl": "https://play.google.com/store/search?q=successkey98&c=apps",
  },
  {
    "projectName": "Hilite Solar",
    "jobTitle": "Flutter Developer",
    "companyName": "Ionstar India Pvt Ltd",
    "url": "http://ionstar.in/",
    "description": "",
    "imageURL": "",
    "appUrl": "",
  },
  {
    "projectName": "Detel",
    "jobTitle": "Flutter Developer",
    "companyName": "Ionstar India Pvt Ltd",
    "url": "http://ionstar.in/",
    "description": "",
    "imageURL": "",
    "appUrl": "",
  },
  {
    "projectName": "Zomme",
    "jobTitle": "Flutter Developer",
    "companyName": "Ionstar India Pvt Ltd",
    "url": "http://ionstar.in/",
    "description": "",
    "imageURL": "",
    "appUrl": "",
  },
  {
    "projectName": "Samod",
    "jobTitle": "Flutter Developer",
    "companyName": "Ionstar India Pvt Ltd",
    "url": "http://ionstar.in/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/IMcs9Gay4UTGV4j93ISRGtrrYjntk5ro2aXE3l33M6-reUUVrR2gzxShtJUXqcy8-Z8=w240-h480-rw",
    "appUrl": "https://play.google.com/store/apps/details?id=com.ionstar.samod",
  },
  {
    "projectName": "Vishal Bharath Textiles",
    "jobTitle": "Flutter Developer",
    "companyName": "Ionstar India Pvt Ltd",
    "url": "http://ionstar.in/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/InpUTyzGEB3yMarmuNgbSpNnorYX1aYNWYRnzUN2tLLQDN1beiqBsErNmsqZF5pQqQ=w240-h480-rw",
    "appUrl": "https://play.google.com/store/apps/details?id=com.ionstar.vbtex",
  },
  {
    "projectName": "Evergreen Farms",
    "jobTitle": "Flutter Developer",
    "companyName": "Ionstar India Pvt Ltd",
    "url": "http://ionstar.in/",
    "description": "",
    "imageURL": "",
    "appUrl": "",
  },
  {
    "projectName": "ESUBA",
    "jobTitle": "Flutter Developer",
    "companyName": "Ionstar India Pvt Ltd",
    "url": "http://ionstar.in/",
    "description": "",
    "imageURL":
        "https://play-lh.googleusercontent.com/xXzmCo_o7gmcObcCUBGEExxYwSnJyP_8YiptYPA_GGVO_h-aE6for80XwDTn9WClaB-E=w240-h480-rw",
    "appUrl": "https://play.google.com/store/apps/details?id=com.ionstar.esuba",
  },
  {
    "projectName": "Unosales",
    "jobTitle": "Flutter Developer",
    "companyName": "Ionstar India Pvt Ltd",
    "url": "http://ionstar.in/",
    "description": "",
    "imageURL": "",
    "appUrl": "",
  },
  {
    "projectName": "ABA Corporation",
    "jobTitle": "Flutter Developer",
    "companyName": "Ionstar India Pvt Ltd",
    "url": "http://ionstar.in/",
    "description": "",
    "imageURL": "",
    "appUrl": "",
  },
  {
    "projectName": "Hilite UPS",
    "jobTitle": "Flutter Developer",
    "companyName": "Ionstar India Pvt Ltd",
    "url": "http://ionstar.in/",
    "description": "",
    "imageURL": "",
    "appUrl": "https://hisol.unosales.com",
  },
];
